In [1]:
import pandas as pd
import numpy as np
from scipy import stats
from scipy.stats import norm
from scipy.stats import chi2_contingency
from scipy.stats import chi2

In [3]:
prashanth = pd.read_csv("BuyerRatio (1).csv")

In [4]:
prashanth

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [5]:
prashanth.head()

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [6]:
prashanth=np.array([[50,142,131,70],[435,1523,1356,750]])

In [12]:
# Chi2 contengency independence test 
# o/p is (Chi2 stats value, p_value, df, expected obsvations)
chi2_contingency

<function scipy.stats.contingency.chi2_contingency(observed, correction=True, lambda_=None)>

In [13]:
# the p value is 0.6603 is greter than the a therefore the null hypothesis is acceptttted.

In [14]:
data=pd.read_csv("BuyerRatio (1).csv")

In [15]:
data

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [16]:
data.head()

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

# make a dimentional array

In [17]:
data=np.array([[50,142,131,70],[435,1523,1356,750]])
data

array([[  50,  142,  131,   70],
       [ 435, 1523, 1356,  750]])

In [18]:
stat, p, dof, expected=chi2_contingency(data)
alpha=0.05
print("p value is" + str(p))
if p <=alpha:
    print('Dependent(reject H0)')
else:
    print('independent(H0 Hold true)')

p value is0.6603094907091882
independent(H0 Hold true)


In [19]:
stat, p, dof, expected = chi2_contingency(data)
  
# interpret p-value
alpha = 0.05 #95% confidence
print("p value is " + str(p))
if p <= alpha:
    print('Dependent (reject H0)')
else:
    print('Independent (H0 holds true)')


p value is 0.6603094907091882
Independent (H0 holds true)


In [20]:
stat

1.595945538661058

In [21]:
p

0.6603094907091882

In [22]:
dof

3

## OR

In [23]:
data=np.array([[50,142,131,70],[435,1523,1356,750]])
data

array([[  50,  142,  131,   70],
       [ 435, 1523, 1356,  750]])

In [24]:
val=stats.chi2_contingency(data)
val

(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [25]:
stat

1.595945538661058

In [26]:
p

0.6603094907091882

In [27]:
dof

3

In [29]:
expected

array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
       [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]])